
- name: modify existing VM
  hosts: localhost
  connection: local
  gather_facts: no
  become: false
  tasks:
  - name: modify VM with Disk
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pw }}"
      datacenter: "{{ vcenter_dc }}"
      cluster: "{{ vcenter_cluster }}"
      folder: "{{ vcenter_dc }}/{{ folder }}"
      validate_certs: false
      state: "present"
      name: "{{ vm_name }}"
      disk:
      - size_gb: 120
        type: thin
      - size_gb: "{{ vm_add_disksize }}"
        type: thin
        datastore: "{{ vcenter_datastore }}"
    register: vm_disk
