- name: convert hosts from csv
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    vcenter_template: rhel_76
    vm_name: testvm00
    vm_network: "VM Network"
    vm_ip: "1.1.1.2"
    vm_netmask: "255.255.255.0"
    vm_gw: "1.1.1.1"
    vm_init_disksize: 100
    vm_init_mem: 512
    vm_init_cpu: 1
  tasks:
    - name: create VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pw }}"
        validate_certs: False
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_dc }}"
        folder: /
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ vcenter_template }}"
        disk:
        - size_gb: "{{ vm_init_disksize }}"
          type: thin
          datastore: "{{ vcenter_datastore }}"
        hardware:
          memory_mb: "{{ vm_init_mem }}"
          num_cpus: "{{ vm_init_cpu }}"
        networks:
        - name: "{{ vm_network }}"
          type: "static"
          ip: "{{ vm_ip }}"
          netmask: "{{ vm_netmask }}"
          gateway: "{{ vm_gw }}"
        wait_for_ip_address: no
