- name: create PG in DVS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    vlan_name: 1009_VLAN_temp
    vlan_id: 1009
    DVS_name: "labDVS"
  tasks:
    - name: create additional portgroups in named DVS
      local_action:
         module: vmware_dvs_portgroup
         vCenter_hostname: "{{ vcenter_name }}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         portgroup_name: "{{ PG_name }}"
         switch_name: "{{ DVS_name }}"
         vlan_id: "{{ PG_vlan }}"
         num_ports: "{{ PG_portcount }}"
         portgroup_type: earlyBinding
         state: present
