- name: create PG in VSS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    vlan_name: 1009_VLAN_temp
    vlan_id: 1009
    VSS_name: "vSwitch0"
  tasks:
    - name: Create Management portgroup
      local_action:
        module: vmware_portgroup
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pw }}"
        validate_certs: False
        portgroup_name: "{{ vlan_name }}"
        switch_name: "{{ VSS_name }}"
        vlan_id: "{{ vlan_id }}"
        num_ports: 10
        portgroup_type: earlyBinding
        state: present
        network_policy:
          promiscuous_mode: False
