- name: modify existing VM
  hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    folder: /cf
  tasks:
    - name: stop VM
      vmware_guest: 
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pw }}"
        datacenter: "{{ vcenter_dc }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ folder }}"
        validate_certs: false
        state: "poweredoff"
        name: "{{ vm_name }}"
      
    - name: modify VM
      vmware_guest:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pw }}"
        datacenter: "{{ vcenter_dc }}"
        cluster: "{{ vcenter_cluster }}"
        folder: "{{ folder }}"
        validate_certs: false
        state: "present"
        name: "{{ vm_name }}"
        hardware:
          memory_mb: "{{ vm_mem }}"
          num_cpus:  "{{ vm_cpu }}"
        networks:
        - name: "{{ vm_net }}"
    
