---
- name: check DVS presence
  hosts: vCenter
  connection: local
  gather_facts: false
  become: false
  roles:
    - pre-check

- name: create apppool
  hosts: vCenter
  roles:
    - AppPool

- name: create PG
  hosts: vCenter
  connection: local
  gather_facts: false
  become: false
  roles:
    - PG
